train_datadyn = load('danedynucz33.txt')
val_datadyn =  load('danedynwer33.txt')


X_val_dyn_visual = linspace(1,size(val_datadyn,1),size(val_datadyn,1))
X_train_dyn_visual = linspace(1,size(train_datadyn,1),size(train_datadyn,1))
Y_val_dyn_visual = val_datadyn(:,2)
U_val_dyn_visual = val_datadyn(:,1)
Y_train_dyn_visual = train_datadyn(:,2)
U_train_dyn_visual = train_datadyn(:,1)
figure
subplot(2,1,1)
scatter(X_train_dyn_visual,Y_train_dyn_visual,12,"filled",'r')
title("Wykres Y(k)")
xlabel("K - numer próbki")
ylabel("Y - sygnał wyjściowy")
subplot(2,1,2)
scatter(X_train_dyn_visual,U_train_dyn_visual,3,"filled",'r')
title("Wykres U(k)")
xlabel("K - numer próbki")
ylabel("U - sygnał wejściowy")
print('zad2atrenignowe.png','-dpng','-r400')
figure
subplot(2,1,1)
scatter(X_val_dyn_visual,Y_val_dyn_visual,12,"filled",'r')
title("Wykres Y(k)")
xlabel("K - numer próbki")
ylabel("Y - sygnał wyjściowy")
subplot(2,1,2)
scatter(X_val_dyn_visual,U_val_dyn_visual,3,"filled",'r')
title("Wykres U(k)")
xlabel("K - numer próbki")
ylabel("U - sygnał wejściowy")
print('zad2walidacyjne.png','-dpng','-r400')